config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions'}
  resources :users, except: [:new]
  resources :carousel_cards
  resources :mini_cards
  resources :featurettes
  resources :reviews, only: [:new, :create, :edit, :update, :destroy]
  resources :members
  resources :professions
  resources :specialties
  resources :articles

  get 'admin', to: 'admin#general'
  get 'team-members', to: 'admin#team_members'
  get 'medical-appliances', to: 'admin#medical_appliances'
  get 'blog-admin', to: 'admin#blog_admin'

  root to: 'pages#home'
  get 'despre-noi', to: 'pages#about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get '*any', via: :all, to: 'errors#not_found'
end

app/views/shared/_footer.html.erb
<footer>
  <ul class="nav justify-content-center border-bottom">
    <li class="nav-item"><%= link_to 'Echipa', root_path, class: 'nav-link px-2 text-muted link-to' %></li>
    <li class="nav-item"><%= link_to 'Specialități', root_path, class: 'nav-link px-2 text-muted link-to' %></li>
    <li class="nav-item"><%= link_to 'Pacienți', root_path, class: 'nav-link px-2 text-muted link-to' %></li>
    <li class="nav-item"><%= link_to 'Despre Spinal Care', root_path, class: 'nav-link px-2 text-muted link-to' %></li>
  </ul>
  <div class="footer-about">
    <%#= image_tag('logo2.png') %>
    <div class="footer-spinal-locations">
      <!-- <div class="location-1">
        <hr>
        adresa <i class="fa-solid fa-house"></i> adresa
      </div> -->
    </div>
  </div>
  <p class="text-center text-muted">&copy; 2000 - <%= Time.now.year %> Spinal Care</p>
</footer>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag('logo2.png') %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <li class="nav-item active">
          <%= link_to "Echipa", members_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Specialități", "#", class: "nav-link" %>
        </li>
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Admin", admin_path, class: "nav-link", local: true %>
          </li>
        <% end %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" data-bs-toggle="dropdown" aria-expanded="false">Info</a>
          <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
            <%= link_to "Tehnică medicală", "#", class: "dropdown-item" %>
            <%= link_to "Blog", articles_path, class: "dropdown-item" %>
            <%= link_to "Pacienți", "#", class: "dropdown-item" %>
            <%= link_to "Legea 46/2003", "#", class: "dropdown-item" %>
            <%= link_to "Despre Spinal Care", despre_noi_path, class: "dropdown-item" %>
            <button class="dropdown-item" id="nav-review-btn">Părerea ta</button>
            </div>
          </li>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_sidebar_admins.html.erb
<% if current_user.admin %>
  <div class="d-flex flex-column flex-shrink-0 p-3 text-white bg-dark side-bar-custom" style="width: 10%; min-width: 80px; height: calc(var(--vh) * 100);">
      <span class="fs-4 text-center">App <i class="fas fa-tools"></i></span>
    <hr>
    <ul class="nav nav-pills flex-column mb-auto">
      <li class="nav-item text-center ">
        <%= link_to root_path, class: 'nav-link text-white', aria_current: 'page' do %>
          <i class="fas fa-home"></i>
        <% end %>
      </li>
      <li class="nav-item text-center ">
        <%= link_to admin_path, class: 'nav-link text-white', aria_current: 'page' do %>
        <i class="fas fa-sliders-h"></i>
        <% end %>
      </li>
      <li class="nav-item text-center">
        <%= link_to team_members_path, class: 'nav-link text-white', aria_current: 'page' do %>
          <i class="fas fa-users"></i>
        <% end %>
      </li>
      <li class="nav-item text-center">
        <%= link_to medical_appliances_path, class: 'nav-link text-white', aria_current: 'page' do %>
        <i class="fas fa-briefcase-medical"></i>
        <% end %>
      </li>
      <li class="nav-item text-center">
        <%= link_to blog_admin_path, class: 'nav-link text-white', aria_current: 'page' do %>
        <i class="fas fa-keyboard"></i>
        <% end %>
      </li>
      <hr>
      <li style="font-size: 10px;" class="text-center"><%= current_user.email %></li>
      <li class="nav-item text-center">
        <%= link_to destroy_user_session_path, class: 'nav-link text-white', aria_current: 'page', method: :delete do %>
          <i class="fas fa-sign-out-alt"></i>
        <% end %>
      </li>
    </ul>
  </div>
<% end %>