config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions'}
  resources :users, except: [:new]
  resources :carousel_cards
  resources :mini_cards
  resources :featurettes
  resources :reviews, only: [:new, :create, :edit, :update, :destroy]
  resources :members
  resources :professions
  resources :specialties
  resources :articles

  get 'admin', to: 'admin#general'
  get 'team-members', to: 'admin#team_members'
  get 'medical-appliances', to: 'admin#medical_appliances'
  get 'blog-admin', to: 'admin#blog_admin'

  root to: 'pages#home'
  get 'despre-noi', to: 'pages#about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get '*any', via: :all, to: 'errors#not_found'
end

app/views/partials/admin/general_page/_home_page_section.html.erb
<div class="container-fluid">
  <h3>Administrare home page</h3>
  <hr>
  <div class="carousel-cards-admin" id="carousel-cards-admin">
    <h4>Secțiunea pentru carousel cards</h4>
    <h5>Card nou pentru carousel</h5>
      <%= render 'partials/admin/general_page/render_carousel_admin', existing_card: false, cc: @carousel_card %>
    <h5>Carduri pentru carousel existente</h5>
    <%= render 'partials/admin/general_page/render_carousel_admin', existing_card: true %>
  </div>
  <hr>
    <%= render 'partials/admin/general_page/render_minicards_admin', mc: @mini_card %>
  </div>
  <hr>
  <div class="featurettes-cards-admin" id="featurettes-cards-admin">
    <h4>Secțiunea carduri featurettes</h4>
    <h5>Featurette nou</h5>
      <%= render 'partials/admin/general_page/tables_featurette', existing_featurette: false, featurette: @featurette  %>
    <h5>Carduri pentru featurette existente</h5>
      <div class="featurettes_index mt-5">
        <%= render 'partials/admin/general_page/tables_featurette', existing_featurette: true, featurette: @featurette  %>
      </div>
  </div>
  <hr>
  <%= render 'partials/admin/general_page/reviews_section' %>
</div>

app/views/partials/admin/general_page/_render_carousel_admin.html.erb
  <% if !existing_card %>
    <%= simple_form_for(cc) do |f| %>
      <table class="table">
        <tr>
          <th scope="col">Imagine</th>
          <th scope="col">Titlu</th>
          <th scope="col">Subtitlu</th>
          <th scope="col">Titlu btn</th>
          <th scope="col">Cale buton*</th>
          <th scope="col">Acțiune</th>
        </tr>
        <tr>
          <td><%= f.input :photo, label: false %></td>
          <td><%= f.input :line_one, label: false %></td>
          <td><%= f.input :line_two, label: false %></td>
          <td><%= f.input :btn_text, label: false %></td>
          <td><%= f.input :btn, label: false %></td>
          <td><%= f.submit cc.id ? 'Modifică card' : 'Card nou', class: "btn btn-sm btn-primary #{'disabled' if @carousel_cards.count > 4 && !cc.id }" %></td>
        </th>
      </table>
    <% end %>
  <% elsif existing_card %>
    <% @carousel_cards.each_with_index do |cc, i| %>
    <%= simple_form_for(cc) do |f| %>
      <table class="table">
        <tr class="<%= "header-opacity" if i != 0 %>">
          <th>Imagine</th>
          <th>Schimbă img</th>
          <th>Titlu</th>
          <th>Subtitlu</th>
          <th>Titlu btn</th>
          <th>Cale buton*</th>
          <th>Acțiune</th>
          <th>Șterge</th>
        </tr>
        <tr>
          <td><%= cl_image_tag(cc.photo.key, height: 100, width: 100, crop: :fill) if cc.photo.key %></td>
          <td><%= f.input :photo, label: false %></td>
          <td><%= f.input :line_one, label: false %></td>
          <td><%= f.input :line_two, label: false %></td>
          <td><%= f.input :btn_text, label: false %></td>
          <td><%= f.input :btn, label: false %></td>
          <td><%= f.submit 'Modifică card', class: "btn btn-sm btn-primary" %></td>
          <td><%= link_to '🗑', carousel_card_path(cc), method: :delete %></td>
      </table>
    <% end %>
    <% end %>
  <% end %>

app/views/partials/admin/general_page/_render_minicards_admin.html.erb
<div class="mini-cards-admin" id="mini-cards-admin">
  <h4>Secțiunea pentru mini carduri</h4>
    <div class="new-minicard-section">
      <h5>Minicard nou</h5>
      <div class="new-minicard-section__headers">
        <p>Selectează</p>
        <p class="text-center">Text</p>
        <p>Acțiune</p>
      </div>
      <%= simple_form_for(mc) do |f| %>
      <div class="new-minicard-section__form">
          <span><%= f.input :photo, as: :file, label: false %></span>
          <span><%= f.input :text, label: false %></span>
          <span><%= f.submit 'Card nou' , class: "btn btn-sm btn-primary #{"disabled" if @mini_cards.count > 2 && !mc.id }" %></span>
        </div>
        <% end %>
    </div>
    <div class="minicards-index-section">
      <h5>Carduri pentru carousel existente</h5>
      <div class="minicards-index-section__headers">
        <p>Imagine</p>
        <p>Selectează</p>
        <p class="text-center">Text</p>
        <p>Acțiune</p>
        <p>Șterge</p>
      </div>
      <% @mini_cards.each_with_index do |mc, i| %>
        <%= simple_form_for(mc) do |f| %>
          <div class="minicards-index-section__form">
            <span><%= cl_image_tag(mc.photo.key, height: 100, width: 100, crop: :fill) if mc.photo.key.present? %></span>
            <span><%= f.input :photo, as: :file, label: false %></span>
            <span><%= f.input :text, label: false, class: 'text-center' %></span>
            <span><%= f.submit 'Modifică', class: "btn btn-sm btn-primary" %></span>
            <span><%= link_to '🗑', mini_card_path(mc), method: :delete %></span>
          </div>
        <% end %>
      <% end %>
    </div>
</div>

app/views/partials/admin/general_page/_reviews_section.html.erb
<div class="reviews-section" id="reviews-section">
  <h4 class="mb-5">Secțiunea aprobare/ștergere recenzii</h4>
  <div class="reviews-edit-title">
    <p>Conținut</p>
    <p>Rating</p>
    <p>Aprobat?</p>
    <p>Acțiune</p>
    <p>Șterge</p>
  </div>
  <% @reviews.each do |r| %>
    <%= simple_form_for(r) do |f| %>
      <div class="review-row">
        <span><%= r.content %></span>
        <span><%= r.rating %></span>
        <span><%= f.input :approved, label: false %></span>
        <span><%= f.submit 'Aprobă', class: 'btn btn-primary' %></span>
        <span><%= link_to '🗑', review_path(r), method: :delete %></span>
      </div>
      <hr>
    <% end %>
  <% end %>
</div>

app/views/partials/admin/general_page/_tables_featurette.html.erb
<% if !existing_featurette %>
<%= simple_form_for(featurette) do |f| %>
  <table class="table" style="margin-top: 40px; width: 60vw">
  <tr>
    <th>Img nouă</th>
    <th>Titlu (1)</th>
    <th>Titlu (2)</th>
    <th>Text</th>
    <th>Acțiune</th>
  </tr>
    <tr>
        <td><%= f.input :photo, as: :file, label: false %></td>
        <td><%= f.input :title_one, label: false %></td>
        <td><%= f.input :title_two, label: false %></td>
        <td><%= f.input :content, label: false %></td>
        <td><%= f.submit 'Featurette nou', class: 'btn btn-sm btn-primary' %></td>
      </tr>
    </table>
  <% end %>
    
  <% elsif existing_featurette %>
    <% @featurettes.each_with_index do |ft, i| %>
    <%= simple_form_for(ft) do |f| %>
    <table class="table">
      <tr class="<%= "header-opacity" if i != 0 %>">
        <th>Img</th>
        <th>Img nouă</th>
        <th>Titlu (1)</th>
        <th>Titlu (2)</th>
        <th>Text</th>
        <th>Acțiune</th>
        <th>Șterge</th>
      </tr>
      <tr>
        <td><%= cl_image_tag(ft.photo.key, height: 100, width: 100, crop: :fill) if ft.photo.key.present? %></td>
        <td><%= f.input :photo, as: :file, label: false %></td>
        <td><%= f.input :title_one, label: false %></td>
        <td><%= f.input :title_two, label: false %></td>
        <td><%= f.input :content, label: false %></td>
        <td><%= f.submit 'Modifică', class: 'btn btn-sm btn-primary' %></td>
        <td><%= link_to '🗑', featurette_path(ft), method: :delete %></td>
      </tr>
    </table>
    <% end %>
<% end %>
  <% end %>